import { Weapon, PrimaryAttribute, SecondaryStat, SkillStat } from './types';

export const PRIMARY_ATTRIBUTES: PrimaryAttribute[] = [
  'Agility Boost',
  'Strength Boost',
  'Will Boost',
  'Intellect Boost',
  'Main Attribute Boost',
];

export const SECONDARY_STATS: SecondaryStat[] = [
  'Attack Boost',
  'HP Boost',
  'Physical DMG Boost',
  'Heat DMG Boost',
  'Electric DMG Boost',
  'Cryo DMG Boost',
  'Nature DMG Boost',
  'Critical Rate Boost',
  'Arts Intensity Boost',
  'Ultimate Gain Boost',
  'Arts DMG Boost',
  'Treatment Efficiency Boost',
];

export const SKILL_STATS: SkillStat[] = [
  'Assault',
  'Suppression',
  'Pursuit',
  'Crusher',
  'Inspiring',
  'Combative',
  'Brutality',
  'Infliction',
  'Medicant',
  'Fracture',
  'Detonate',
  'Twilight',
  'Flow',
  'Efficacy',
];

export const WEAPONS: Weapon[] = [
  // 6★ WEAPONS
  {
    id: 'w1',
    name: 'Sundered Prince',
    img: 'https://endfield.wiki.gg/images/Sundered_Prince_icon.png?a6f1f6=&format=original',
    rarity: 6,
    type: 'Great Sword',
    requiredEssence: {
      primary: 'Strength Boost',
      secondary: 'Critical Rate Boost',
      skill: 'Crusher',
    },
  },
  {
    id: 'w2',
    name: 'Artzy Tyrannical',
    img: 'https://picsum.photos/seed/artzy-tyrannical/200/200',
    rarity: 6,
    type: 'Handcannon',
    requiredEssence: {
      primary: 'Intellect Boost',
      secondary: 'Critical Rate Boost',
      skill: 'Fracture',
    },
  },
  {
    id: 'w3',
    name: 'Delivery Guaranteed',
    img: 'https://picsum.photos/seed/delivery-guaranteed/200/200',
    rarity: 6,
    type: 'Arts Unit',
    requiredEssence: {
      primary: 'Will Boost',
      secondary: 'Ultimate Gain Boost',
      skill: 'Pursuit',
    },
  },
  {
    id: 'w4',
    name: 'Forgeborn Scathe',
    img: 'https://picsum.photos/seed/forgeborn-scathe/200/200',
    rarity: 6,
    type: 'Sword',
    requiredEssence: {
      primary: 'Intellect Boost',
      secondary: 'Attack Boost',
      skill: 'Twilight',
    },
  },
  {
    id: 'w5',
    name: 'Thermite Cutter',
    img: 'https://picsum.photos/seed/thermite-cutter/200/200',
    rarity: 6,
    type: 'Sword',
    requiredEssence: {
      primary: 'Will Boost',
      secondary: 'Attack Boost',
      skill: 'Flow',
    },
  },
  {
    id: 'w6',
    name: 'Umbral Torch',
    img: 'https://picsum.photos/seed/umbral-torch/200/200',
    rarity: 6,
    type: 'Sword',
    requiredEssence: {
      primary: 'Intellect Boost',
      secondary: 'Heat DMG Boost',
      skill: 'Infliction',
    },
  },
  {
    id: 'w7',
    name: 'Former Finery',
    img: 'https://picsum.photos/seed/former-finery/200/200',
    rarity: 6,
    type: 'Great Sword',
    requiredEssence: {
      primary: 'Will Boost',
      secondary: 'HP Boost',
      skill: 'Efficacy',
    },
  },
  {
    id: 'w8',
    name: 'Thunderberge',
    img: 'https://picsum.photos/seed/thunderberge/200/200',
    rarity: 6,
    type: 'Great Sword',
    requiredEssence: {
      primary: 'Strength Boost',
      secondary: 'HP Boost',
      skill: 'Medicant',
    },
  },
  {
    id: 'w9',
    name: 'Mountain Bearer',
    img: 'https://picsum.photos/seed/mountain-bearer/200/200',
    rarity: 6,
    type: 'Polearm',
    requiredEssence: {
      primary: 'Agility Boost',
      secondary: 'Physical DMG Boost',
      skill: 'Efficacy',
    },
  },
  {
    id: 'w10',
    name: 'Valiant',
    img: 'https://picsum.photos/seed/valiant/200/200',
    rarity: 6,
    type: 'Polearm',
    requiredEssence: {
      primary: 'Agility Boost',
      secondary: 'Physical DMG Boost',
      skill: 'Combative',
    },
  },
  {
    id: 'w11',
    name: 'Wedge',
    img: 'https://picsum.photos/seed/wedge/200/200',
    rarity: 6,
    type: 'Handcannon',
    requiredEssence: {
      primary: 'Main Attribute Boost',
      secondary: 'Critical Rate Boost',
      skill: 'Infliction',
    },
  },
  {
    id: 'w12',
    name: 'Chivalric Virtues',
    img: 'https://picsum.photos/seed/chivalric-virtues/200/200',
    rarity: 6,
    type: 'Arts Unit',
    requiredEssence: {
      primary: 'Will Boost',
      secondary: 'HP Boost',
      skill: 'Medicant',
    },
  },
  {
    id: 'w13',
    name: 'Detonation Unit',
    img: 'https://picsum.photos/seed/detonation-unit/200/200',
    rarity: 6,
    type: 'Arts Unit',
    requiredEssence: {
      primary: 'Main Attribute Boost',
      secondary: 'Arts Intensity Boost',
      skill: 'Detonate',
    },
  },
  {
    id: 'w14',
    name: 'Oblivion',
    img: 'https://picsum.photos/seed/oblivion/200/200',
    rarity: 6,
    type: 'Arts Unit',
    requiredEssence: {
      primary: 'Intellect Boost',
      secondary: 'Arts DMG Boost',
      skill: 'Twilight',
    },
  },
  {
    id: 'w15',
    name: 'Opus: Etch Figure',
    img: 'https://picsum.photos/seed/opus-etch-figure/200/200',
    rarity: 6,
    type: 'Arts Unit',
    requiredEssence: {
      primary: 'Will Boost',
      secondary: 'Nature DMG Boost',
      skill: 'Suppression',
    },
  },
  {
    id: 'w16',
    name: 'Grand Vision',
    img: 'https://picsum.photos/seed/grand-vision/200/200',
    rarity: 6,
    type: 'Sword',
    requiredEssence: {
      primary: 'Agility Boost',
      secondary: 'Attack Boost',
      skill: 'Infliction',
    },
  },
  {
    id: 'w17',
    name: 'Never Rest',
    img: 'https://picsum.photos/seed/never-rest/200/200',
    rarity: 6,
    type: 'Sword',
    requiredEssence: {
      primary: 'Will Boost',
      secondary: 'Attack Boost',
      skill: 'Flow',
    },
  },
  {
    id: 'w18',
    name: 'Rapid Ascent',
    img: 'https://picsum.photos/seed/rapid-ascent/200/200',
    rarity: 6,
    type: 'Sword',
    requiredEssence: {
      primary: 'Main Attribute Boost',
      secondary: 'Critical Rate Boost',
      skill: 'Twilight',
    },
  },
  {
    id: 'w19',
    name: 'Eminent Repute',
    img: 'https://picsum.photos/seed/eminent-repute/200/200',
    rarity: 6,
    type: 'Sword',
    requiredEssence: {
      primary: 'Main Attribute Boost',
      secondary: 'Physical DMG Boost',
      skill: 'Brutality',
    },
  },
  {
    id: 'w20',
    name: 'White Night Nova',
    img: 'https://picsum.photos/seed/white-night-nova/200/200',
    rarity: 6,
    type: 'Sword',
    requiredEssence: {
      primary: 'Main Attribute Boost',
      secondary: 'Arts Intensity Boost',
      skill: 'Infliction',
    },
  },
  {
    id: 'w21',
    name: 'Khravengger',
    img: 'https://picsum.photos/seed/khravengger/200/200',
    rarity: 6,
    type: 'Great Sword',
    requiredEssence: {
      primary: 'Strength Boost',
      secondary: 'Attack Boost',
      skill: 'Detonate',
    },
  },
  {
    id: 'w22',
    name: 'Exemplar',
    img: 'https://picsum.photos/seed/exemplar/200/200',
    rarity: 6,
    type: 'Great Sword',
    requiredEssence: {
      primary: 'Main Attribute Boost',
      secondary: 'Attack Boost',
      skill: 'Suppression',
    },
  },
  {
    id: 'w23',
    name: 'JET',
    img: 'https://picsum.photos/seed/jet/200/200',
    rarity: 6,
    type: 'Polearm',
    requiredEssence: {
      primary: 'Main Attribute Boost',
      secondary: 'Attack Boost',
      skill: 'Suppression',
    },
  },
  {
    id: 'w24',
    name: 'Navigator',
    img: 'https://picsum.photos/seed/navigator/200/200',
    rarity: 6,
    type: 'Handcannon',
    requiredEssence: {
      primary: 'Intellect Boost',
      secondary: 'Cryo DMG Boost',
      skill: 'Infliction',
    },
  },
  {
    id: 'w25',
    name: 'Clannibal',
    img: 'https://picsum.photos/seed/clannibal/200/200',
    rarity: 6,
    type: 'Handcannon',
    requiredEssence: {
      primary: 'Main Attribute Boost',
      secondary: 'Arts DMG Boost',
      skill: 'Infliction',
    },
  },
  {
    id: 'w26',
    name: 'Dreams of the Starry Beach',
    img: 'https://picsum.photos/seed/dreams-of-the-starry-beach/200/200',
    rarity: 6,
    type: 'Arts Unit',
    requiredEssence: {
      primary: 'Intellect Boost',
      secondary: 'Treatment Efficiency Boost',
      skill: 'Infliction',
    },
  },

  // 5★ WEAPONS
  {
    id: 'w27',
    name: 'Sundering Steel',
    img: 'https://picsum.photos/seed/sundering-steel/200/200',
    rarity: 5,
    type: 'Sword',
    requiredEssence: {
      primary: 'Agility Boost',
      secondary: 'Physical DMG Boost',
      skill: 'Combative',
    },
  },
  {
    id: 'w28',
    name: 'Wild Wanderer',
    img: 'https://picsum.photos/seed/wild-wanderer/200/200',
    rarity: 5,
    type: 'Arts Unit',
    requiredEssence: {
      primary: 'Intellect Boost',
      secondary: 'Electric DMG Boost',
      skill: 'Infliction',
    },
  },
  {
    id: 'w29',
    name: 'Fortmaker',
    img: 'https://picsum.photos/seed/fortmaker/200/200',
    rarity: 5,
    type: 'Sword',
    requiredEssence: {
      primary: 'Intellect Boost',
      secondary: 'Ultimate Gain Boost',
      skill: 'Inspiring',
    },
  },
  {
    id: 'w30',
    name: 'Finishing Call',
    img: 'https://picsum.photos/seed/finishing-call/200/200',
    rarity: 5,
    type: 'Great Sword',
    requiredEssence: {
      primary: 'Strength Boost',
      secondary: 'HP Boost',
      skill: 'Medicant',
    },
  },
  {
    id: 'w31',
    name: 'Chimeric Justice',
    img: 'https://picsum.photos/seed/chimeric-justice/200/200',
    rarity: 5,
    type: 'Polearm',
    requiredEssence: {
      primary: 'Strength Boost',
      secondary: 'Ultimate Gain Boost',
      skill: 'Brutality',
    },
  },
  {
    id: 'w32',
    name: 'Rational Farewell',
    img: 'https://picsum.photos/seed/rational-farewell/200/200',
    rarity: 5,
    type: 'Handcannon',
    requiredEssence: {
      primary: 'Strength Boost',
      secondary: 'Heat DMG Boost',
      skill: 'Pursuit',
    },
  },
  {
    id: 'w33',
    name: 'Monaihe',
    img: 'https://picsum.photos/seed/monaihe/200/200',
    rarity: 5,
    type: 'Arts Unit',
    requiredEssence: {
      primary: 'Will Boost',
      secondary: 'Ultimate Gain Boost',
      skill: 'Inspiring',
    },
  },
  {
    id: 'w34',
    name: 'Stanza of Memorials',
    img: 'https://picsum.photos/seed/stanza-of-memorials/200/200',
    rarity: 5,
    type: 'Arts Unit',
    requiredEssence: {
      primary: 'Intellect Boost',
      secondary: 'Attack Boost',
      skill: 'Twilight',
    },
  },
  {
    id: 'w35',
    name: 'Finchaser 3.0',
    img: 'https://picsum.photos/seed/finchaser-3-0/200/200',
    rarity: 5,
    type: 'Sword',
    requiredEssence: {
      primary: 'Strength Boost',
      secondary: 'Cryo DMG Boost',
      skill: 'Suppression',
    },
  },
  {
    id: 'w36',
    name: 'Twelve Questions',
    img: 'https://picsum.photos/seed/twelve-questions/200/200',
    rarity: 5,
    type: 'Sword',
    requiredEssence: {
      primary: 'Agility Boost',
      secondary: 'Attack Boost',
      skill: 'Infliction',
    },
  },
  {
    id: 'w37',
    name: 'OBJ Edge of Lightness',
    img: 'https://picsum.photos/seed/obj-edge-of-lightness/200/200',
    rarity: 5,
    type: 'Sword',
    requiredEssence: {
      primary: 'Agility Boost',
      secondary: 'Attack Boost',
      skill: 'Flow',
    },
  },
  {
    id: 'w38',
    name: 'Aspirant',
    img: 'https://picsum.photos/seed/aspirant/200/200',
    rarity: 5,
    type: 'Sword',
    requiredEssence: {
      primary: 'Agility Boost',
      secondary: 'Physical DMG Boost',
      skill: 'Twilight',
    },
  },
  {
    id: 'w39',
    name: 'Seeker of Dark Lung',
    img: 'https://picsum.photos/seed/seeker-of-dark-lung/200/200',
    rarity: 5,
    type: 'Great Sword',
    requiredEssence: {
      primary: 'Strength Boost',
      secondary: 'Ultimate Gain Boost',
      skill: 'Detonate',
    },
  },
  {
    id: 'w40',
    name: 'Ancient Canal',
    img: 'https://picsum.photos/seed/ancient-canal/200/200',
    rarity: 5,
    type: 'Great Sword',
    requiredEssence: {
      primary: 'Strength Boost',
      secondary: 'Arts Intensity Boost',
      skill: 'Brutality',
    },
  },
  {
    id: 'w41',
    name: 'OBJ Heavy Burden',
    img: 'https://picsum.photos/seed/obj-heavy-burden/200/200',
    rarity: 5,
    type: 'Great Sword',
    requiredEssence: {
      primary: 'Strength Boost',
      secondary: 'HP Boost',
      skill: 'Efficacy',
    },
  },
  {
    id: 'w42',
    name: 'OBJ Razorhorn',
    img: 'https://picsum.photos/seed/obj-razorhorn/200/200',
    rarity: 5,
    type: 'Polearm',
    requiredEssence: {
      primary: 'Will Boost',
      secondary: 'Physical DMG Boost',
      skill: 'Infliction',
    },
  },
  {
    id: 'w43',
    name: 'Opus: The Living',
    img: 'https://picsum.photos/seed/opus-the-living/200/200',
    rarity: 5,
    type: 'Handcannon',
    requiredEssence: {
      primary: 'Agility Boost',
      secondary: 'Arts DMG Boost',
      skill: 'Infliction',
    },
  },
  {
    id: 'w44',
    name: 'OBJ Velocitous',
    img: 'https://picsum.photos/seed/obj-velocitous/200/200',
    rarity: 5,
    type: 'Handcannon',
    requiredEssence: {
      primary: 'Agility Boost',
      secondary: 'Ultimate Gain Boost',
      skill: 'Detonate',
    },
  },
  {
    id: 'w45',
    name: 'Freedom to Proselytize',
    img: 'https://picsum.photos/seed/freedom-to-proselytize/200/200',
    rarity: 5,
    type: 'Arts Unit',
    requiredEssence: {
      primary: 'Will Boost',
      secondary: 'Treatment Efficiency Boost',
      skill: 'Medicant',
    },
  },
  {
    id: 'w46',
    name: 'OBJ Arts Identifier',
    img: 'https://picsum.photos/seed/obj-arts-identifier/200/200',
    rarity: 5,
    type: 'Arts Unit',
    requiredEssence: {
      primary: 'Intellect Boost',
      secondary: 'Arts Intensity Boost',
      skill: 'Pursuit',
    },
  },
  {
    id: 'w47',
    name: 'Cohesive Traction',
    img: 'https://picsum.photos/seed/cohesive-traction/200/200',
    rarity: 5,
    type: 'Polearm',
    requiredEssence: {
      primary: 'Will Boost',
      secondary: 'Electric DMG Boost',
      skill: 'Suppression',
    },
  },

  // 4★ WEAPONS
  {
    id: 'w48',
    name: "Pathfinder's Beacon",
    img: 'https://picsum.photos/seed/pathfinders-beacon/200/200',
    rarity: 4,
    type: 'Polearm',
    requiredEssence: {
      primary: 'Agility Boost',
      secondary: 'Attack Boost',
      skill: 'Inspiring',
    },
  },
  {
    id: 'w49',
    name: 'Industry 0.1',
    img: 'https://picsum.photos/seed/industry-0-1/200/200',
    rarity: 4,
    type: 'Great Sword',
    requiredEssence: {
      primary: 'Strength Boost',
      secondary: 'Attack Boost',
      skill: 'Suppression',
    },
  },
  {
    id: 'w50',
    name: 'Howling Guard',
    img: 'https://picsum.photos/seed/howling-guard/200/200',
    rarity: 4,
    type: 'Handcannon',
    requiredEssence: {
      primary: 'Intellect Boost',
      secondary: 'Attack Boost',
      skill: 'Suppression',
    },
  },
  {
    id: 'w51',
    name: 'Contingent Measure',
    img: 'https://picsum.photos/seed/contingent-measure/200/200',
    rarity: 4,
    type: 'Sword',
    requiredEssence: {
      primary: 'Agility Boost',
      secondary: 'Physical DMG Boost',
      skill: 'Suppression',
    },
  },
  {
    id: 'w52',
    name: 'Aggeloslayer',
    img: 'https://picsum.photos/seed/aggeloslayer/200/200',
    rarity: 4,
    type: 'Polearm',
    requiredEssence: {
      primary: 'Will Boost',
      secondary: 'Arts DMG Boost',
      skill: 'Suppression',
    },
  },
  {
    id: 'w53',
    name: 'Long Road',
    img: 'https://picsum.photos/seed/long-road/200/200',
    rarity: 4,
    type: 'Handcannon',
    requiredEssence: {
      primary: 'Strength Boost',
      secondary: 'Arts DMG Boost',
      skill: 'Pursuit',
    },
  },
  {
    id: 'w54',
    name: 'Hypernova Auto',
    img: 'https://picsum.photos/seed/hypernova-auto/200/200',
    rarity: 4,
    type: 'Arts Unit',
    requiredEssence: {
      primary: 'Intellect Boost',
      secondary: 'Arts DMG Boost',
      skill: 'Inspiring',
    },
  },
  {
    id: 'w55',
    name: 'Wave Tide',
    img: 'https://picsum.photos/seed/wave-tide/200/200',
    rarity: 4,
    type: 'Sword',
    requiredEssence: {
      primary: 'Intellect Boost',
      secondary: 'Attack Boost',
      skill: 'Pursuit',
    },
  },
  {
    id: 'w56',
    name: 'Quencher',
    img: 'https://picsum.photos/seed/quencher/200/200',
    rarity: 4,
    type: 'Great Sword',
    requiredEssence: {
      primary: 'Will Boost',
      secondary: 'HP Boost',
      skill: 'Crusher',
    },
  },
  {
    id: 'w57',
    name: 'Fluorescent Roc',
    img: 'https://picsum.photos/seed/fluorescent-roc/200/200',
    rarity: 4,
    type: 'Arts Unit',
    requiredEssence: {
      primary: 'Will Boost',
      secondary: 'Attack Boost',
      skill: 'Suppression',
    },
  },
];
